---
kind: pipeline
type: docker
name: coding-standard-php7.0

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-proftp-php7.0-mariadb10.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.0
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: proftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"proftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: proftp
  pull: always
  image: hauptmedia/proftpd
  environment:
    FTP_PASSWORD: test
    FTP_USERNAME: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-proftp-php7.1-mariadb10.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: proftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"proftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: proftp
  pull: always
  image: hauptmedia/proftpd
  environment:
    FTP_PASSWORD: test
    FTP_USERNAME: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-proftp-php7.2-mariadb10.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: proftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"proftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: proftp
  pull: always
  image: hauptmedia/proftpd
  environment:
    FTP_PASSWORD: test
    FTP_USERNAME: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-proftp-php7.3-mariadb10.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: proftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"proftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: proftp
  pull: always
  image: hauptmedia/proftpd
  environment:
    FTP_PASSWORD: test
    FTP_USERNAME: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-vsftp-php7.0-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.0
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: vsftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"vsftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: vsftp
  pull: always
  image: fauria/vsftpd
  environment:
    FTP_PASS: test
    FTP_USER: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-vsftp-php7.1-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: vsftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"vsftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: vsftp
  pull: always
  image: fauria/vsftpd
  environment:
    FTP_PASS: test
    FTP_USER: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-vsftp-php7.2-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: vsftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"vsftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: vsftp
  pull: always
  image: fauria/vsftpd
  environment:
    FTP_PASS: test
    FTP_USER: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-vsftp-php7.3-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_ftp

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/files_external_ftp
    version: daily-master-qa

- name: setup-server-files_external_ftp
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_ftp
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: vsftp-setup
  pull: always
  image: owncloudci/php:7.2
  commands:
  - echo '{"host":"vsftp","username":"test","password":"test"}' > tests/unit/config.json

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: vsftp
  pull: always
  image: fauria/vsftpd
  environment:
    FTP_PASS: test
    FTP_USER: test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

depends_on:
- phpunit-proftp-php7.0-mariadb10.2
- phpunit-proftp-php7.1-mariadb10.2
- phpunit-proftp-php7.2-mariadb10.2
- phpunit-proftp-php7.3-mariadb10.2
- phpunit-vsftp-php7.0-mysql5.5
- phpunit-vsftp-php7.1-mysql5.5
- phpunit-vsftp-php7.2-mysql5.5
- phpunit-vsftp-php7.3-mysql5.5

...
