workspace:
  base: /var/www/owncloud
  path: apps/files_external_ftp


pipeline:
  install-core:
    image: owncloudci/core
    version: ${OC_VERSION}
    pull: true
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_CORE: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e files_external_ftp
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 2
    when:
      matrix:
        NEED_INSTALL_APP: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpstan:
    # phpstan requires php7.1
    image: owncloudci/php:7.1
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/files_external_ftp/.cache/composer
    commands:
      - make test-php-phpstan
    when:
      matrix:
        TEST_SUITE: phpstan

  phan-70:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.0
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/files_external_ftp/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan-70

  phan-71:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.1
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/files_external_ftp/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  phan-72:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.2
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/files_external_ftp/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  phan-73:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.3
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/files_external_ftp/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  proftp-setup:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - echo '{"host":"proftp","username":"test","password":"test"}' > tests/unit/config.json
    when:
      matrix:
        FTP_TYPE: proftp

  vsftp-setup:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - echo '{"host":"vsftp","username":"test","password":"test"}' > tests/unit/config.json
    when:
      matrix:
        FTP_TYPE: vsftp

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
      - tests/output/*.xml
    when:
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [slack_webhook]
    channel: builds
    when:
      status: [failure, changed]
      event: [push, tag]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
      - ORACLE_USER=system
      - ORACLE_PASSWORD=oracle
      - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: oci

  proftp:
    image: hauptmedia/proftpd
    pull: true
    environment:
      - FTP_USERNAME=test
      - FTP_PASSWORD=test
    when:
      matrix:
        FTP_TYPE: proftp

  vsftp:
    image: fauria/vsftpd
    pull: true
    environment:
      - FTP_USER=test
      - FTP_PASS=test
    when:
      matrix:
        FTP_TYPE: vsftp

matrix:
  include:
    # owncloud-coding-standard
    - PHP_VERSION: 7.0
      TEST_SUITE: owncloud-coding-standard

    - PHP_VERSION: 7.1
      TEST_SUITE: owncloud-coding-standard

    - PHP_VERSION: 7.2
      TEST_SUITE: owncloud-coding-standard

    # Unit Tests
    # Using proftp
    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: proftp

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: proftp

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: proftp
      COVERAGE: true

    # Using vsftp
    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: vsftp

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: vsftp

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      FTP_TYPE: vsftp
